objects/Camping_Item__c.object
<CustomObject>
    <fields>
        <fullName>Packed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Camping Item</label>
    <nameField>
        <label>Camping Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampingListController.cls
// Created for CampingList lightning compoment
public with sharing class CampingListController{

  @AuraEnabled
  public static List<Camping_Item__c> getItems(){
      return [Select id, Name, Price__c, Quantity__c, Packed__c from Camping_Item__c];
  }
  
  @AuraEnabled
  public static Camping_Item__c saveItem(Camping_Item__c item){
      try {
          insert item;
      }catch(Exception ex){
      
      }
      return item;
  }


}